name: CI
on:
  push:
    branches: [master]
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: redpwn/admin-bot
          tag_with_ref: true
          tag_with_sha: true
          push: true
